version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    image: shutter_app:dev
    container_name: shutter-app
    #command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - VIRTUAL_HOST=shutter.localhost
      - VIRTUAL_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - vscode-extensions-bun-docker:/root/.vscode-server/extensions
volumes:
  vscode-extensions-bun-docker:
networks:
  proxy:
    external: true
    name: proxy_net

